# Generated by Django 4.0.2 on 2022-02-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='molecuar_weight',
            new_name='molecular_weight',
        ),
    ]
