# Generated by Django 4.0.2 on 2022-02-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_rename_molecuar_weight_analysis_molecular_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_point',
            new_name='samplepoint',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='samping_date',
            new_name='sampling_date',
        ),
    ]
