# Generated by Django 4.0.2 on 2022-02-20 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.metadata')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.test')),
            ],
        ),
    ]
