# Generated by Django 4.0.2 on 2022-02-21 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_testmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StiffTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StiffTemplateLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stiff_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.stifftemplate')),
            ],
        ),
        migrations.CreateModel(
            name='StiffTemplateLevelIon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('stiff_template_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.stifftemplatelevel')),
            ],
        ),
    ]
