# Generated by Django 4.0.2 on 2022-02-22 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_stifftemplate_stifftemplatelevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stifftemplatelevelion',
            name='stiff_template_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stifftemplatelevelions', to='analysis.stifftemplatelevel'),
        ),
    ]
