# Generated by Django 4.0.2 on 2022-02-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_alter_stifftemplatelevelion_stiff_template_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='molecular_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='report_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='testanalysis',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testmetadata',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
