# Generated by Django 4.0.2 on 2022-02-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_alter_analysis_abbreviation_alter_analysis_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
