# Generated by Django 4.0.2 on 2022-03-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_metadata_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='equivalent_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
